### ISSUE TITLE
Add a new object to the map

### ISSUE THREAD

**Issue by robkruger** [djog/djog_unos_2019#80]
Try to understand how the map is made and add a new tree, box or bush to the map

**Comment by Joshua260403** [comment]
or a hedgehog (not the animal, the iron obstacle)

**Comment by Kirsten29** [comment]
Tree added. Hedgehog's next.

**Comment by Kapi369** [comment]
Hello, is it possible to still work on this issue ?

**Comment by richelbilderbeek** [comment]
> Hello, is it possible to still work on this issue ?

@Kapi369: yes, it is! Assign yourself and this Issue is all yours :+1:

**Comment by Kapi369** [comment]
Hey @richelbilderbeek I started to work on it already but seems like i haven't permissions to self-assign issue? Could you assign it to me please?

**Comment by Joshua260403** [comment]
Done :+1:

**Comment by Kapi369** [comment]
Just one more question. I can't make project run. I added java 1.8. Added LWJGL 3 modules to project but it still isn't working. Is there something more I need to do? If so please could you also update readme.md ?

**Comment by Joshua260403** [comment]
What IDE do you use? I use IntelliJ and imported the eclipse project and it
worked without needing to install any libraries manually

Op zo 10 nov. 2019 13:38 schreef Kapi369 <notifications@github.com>:

**Comment by Kapi369** [comment]
Ahh is see now. Version i forked didn't import anything, after importing original project everything works fine.

**Comment by Joshua260403** [comment]
:+1:

Op zo 10 nov. 2019 13:55 schreef Kapi369 <notifications@github.com>:
